Fix a bug about slugs getting broken in a multi-language configuration (#6622)
django-cms/django-cms pull request #6813
Opened 2020-03-04 16:17 UTC by victor-yunenko

## Description

This is a temporary fix for #6622 that simply calls `page._update_title_path(language)` method one more time when a user changes the page slug.

By the way as far as I remember that issue is also solvable by calling `page.save()` method one more time, but this workaround is better targeted at the source of the problem.

## Related resources

https://github.com/divio/django-cms/issues/6622

## Checklist

* [x] I have opened this pull request against ``develop``
* [x] I have updated the **CHANGELOG.rst**
* [ ] I have added or modified the tests when changing logic - again alas I haven't had the time for it. In short this patch is in use on 3-4 projects in live at the moment, with django-cms from 3.5 to 3.7.1. I'm using it as part of [djangocms-helpers](https://pypi.org/project/djangocms-helpers/) package.

2020-09-08 07:42 UTC, FinalAngel commented
@victor-yunenko I^m also not a fan of adding additional requirements. Are there alternatives available? /cc @Aiky30

2020-10-28 11:59 UTC, Aiky30 requested changes
I'm not a fan of temporary work arounds, can we not just fix this in the model directly?

2021-02-12 12:29 UTC, Aiky30 requested changes

2021-02-12 12:29 UTC, Aiky30 commented on cms/signals/slug_update_fix.py
> +This is a temporary fix that should be replaced with an adequate bug fix to the Page logic.
I'd opt to fix this properly rather than bring in a temporary fix that never actually gets fixed.

2021-02-12 12:29 UTC, Aiky30 commented on cms/signals/slug_update_fix.py
> +def fix_title_path(sender, instance, **kwargs):
We do have signals already created, we should just bind to those. V4 reworks the signal in a better fashion.

2021-07-30 00:27 UTC, goutnet commented
@Aiky30 can we look into a more proper fix in 3.9.x then? (since 4.x is  still a long way)

2022-07-28 02:48 UTC, closed without merging