Bugfix/security vulnerabilities
django-cms/django-cms pull request #6930
Opened 2020-10-29 12:43 UTC by adam-murray

## Description

* A number of unsanitised parameters being passed through code were highlighted by checkmarx when we scanned CMS4, this PR covers either sanitising those inputs or providing a test to prove they are non-issues

2020-10-29 15:05 UTC, Aiky30 commented on cms/tests/test_views.py
> +
```suggestion
```

2020-10-29 15:06 UTC, Aiky30 commented on cms/tests/test_views.py
> +
```suggestion
```

2020-10-29 15:07 UTC, Aiky30 approved these changes

2020-11-04 10:52 UTC, Aiky30 requested changes
The two suggestions can be committed from the Github web front but they will still require the import to be manually added due to suggestion limitations.

2020-11-04 10:52 UTC, Aiky30 commented on cms/tests/test_views.py
> +            post_data={"username": user.username, "password": user.username}
```suggestion
            post_data={"username": username, "password": username}
```

@adam-murray This breaks the test suite, I'm not sure why the username field changes for just the Python 3.6 versions. To fix the test suite this needs to be:

```
username = getattr(user, get_user_model().USERNAME_FIELD)
```

Taken from: https://github.com/django-cms/django-cms/blob/f30f0204a8c3e498aa86de0aba35470521859873/cms/tests/test_no_i18n.py#L121

**With the suggestions above you'll still need to add the get_user_model() import at the top of the file:**
```
from django.contrib.auth import get_user_model
```

2020-11-04 10:52 UTC, Aiky30 commented on cms/tests/test_views.py
> +        user = self.get_superuser()
```suggestion
        username = getattr(self.get_superuser(), get_user_model().USERNAME_FIELD)
```

2020-11-04 11:19 UTC, Aiky30 approved these changes
All good. Thanks.

2020-11-04 12:02 UTC, yakky approved these changes

2020-11-05 07:45 UTC, FinalAngel approved these changes

2020-11-05 10:40 UTC, merged