Don't count users when CMS_RAW_ID_USERS=True
django-cms/django-cms pull request #6945
Opened 2020-11-16 11:55 UTC by Pankrat

## Description

When using CMS_RAW_ID_USERS=True on a Postgres database with many users, counting the users is slow and will always yield the same result.

Only count users when using an integer value as a threshold and reuse the same logic for both `PagePermissionInlineAdmin` and
`GlobalPagePermissionAdmin`.

### Background

When looking into performance issues for one of our websites, we found that Django CMS would regularly count all users in our Postgres database. Unfortunately, `SELECT COUNT(*) FROM huge_table` is slow in Postgres and easily takes 500ms or more if you have more than a million records in your table (exact numbers depend on the DB host of course).

I first looked into [improving the speed of the count query](https://www.cybertec-postgresql.com/en/postgresql-count-made-fast/), but this is not easy to achieve in a way that is compatible with different DB backends.

The easiest option was to not run this query at all when using the documented and widely used (AFAICT) `CMS_RAW_ID_USERS = True`.

The change should be backward compatible with the following exceptions:

* `CMS_RAW_ID_USERS = True` will use raw IDs, even if you have just one or zero users in the DB (since `2 > True` but not `1 >  True` in Python). Since the current behavior could be considered a (rather academic) bug, I don't think this is a deal-breaker.
* `CMS_RAW_ID_USERS = 0` will trigger a count and use raw IDs when there's one user or more. If that's a problem, I could check if `threshold` is "truthy" like in the original implementation.

## Checklist

* [x] I have opened this pull request against ``develop``
* [x] I have updated the **CHANGELOG.rst**
* [x] I have added or modified the tests when changing logic

2021-08-19 09:01 UTC, marksweb approved these changes
Nicely done 👍

2022-01-09 18:51 UTC, vinitkumar requested changes
Looks good. @Pankrat can you please rebase/merge with teh latest develop and also fix the flake8 errors if any?

2022-01-19 14:29 UTC, Pankrat commented
Hi @vinitkumar, it seems my earlier rebase ran into the [colors/faker issue on the CI system](https://github.com/django-cms/django-cms/runs/4766229157?check_suite_focus=true). I've just rebased again - hoping this now runs through.

2022-08-31 21:38 UTC, marksweb requested changes

2022-08-31 21:38 UTC, marksweb commented on cms/admin/permissionadmin.py
> +    if threshold is True or threshold is False:
I feel like there should be some more explicit type checking done here if the type we're interested in is an `int`

2022-10-20 13:21 UTC, fsbraun commented
Merged through #7414

2022-10-20 13:21 UTC, closed without merging