WiP: compatibility matrix update Q2 2022
django-cms/django-cms pull request #7313
Opened 2022-05-05 08:53 UTC by macolo

## Description

This is about introducing django-cms 3.10 and 3.11 to the [compatibility table](https://docs.django-cms.org/en/develop/#software-version-requirements-and-release-notes).

## Related resources

* https://github.com/django-cms/django-cms/issues/7312

## Checklist

* [x] I have opened this pull request against ``develop``
* [x] I have added or modified the tests when changing logic
* [ ] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

2022-05-05 08:59 UTC, Aiky30 commented on docs/index.rst
> +4.2.x        ✓    ✓   ✓   ×   ×   ×   ×     ✓   ✓   ×   ×   ×   ×   ×   ×
@macolo There is no 4.2.x unless there are plans that I am not aware of. 
```suggestion
```

2022-05-05 09:02 UTC, Aiky30 commented on docs/index.rst
> +4.0.x        ✓    ✓   ✓   ✓   ×   ×   ×     ✓   ✓   ×   ×   ×   ×   ×   ×
My apologies for the misinformation regarding 3.11 having the same conditions as 4.0, I forgot about the newer python 3.10 and django 4.0 changes. The v4 branches aren't yet structured in a way that we can start adding those changes. 

```suggestion
4.0.x      ×    ✓   ✓   ✓   ×   ×   ×     ×   ✓   ✓   ✓   ✓   ×   ×   ×
```

2022-05-05 09:02 UTC, Aiky30 requested changes
Some changes needed for the V4 compatibility.

2022-05-26 16:17 UTC, Aiky30 approved these changes
django-cms v4 is correct @macolo. :-)

2022-05-27 22:16 UTC, marksweb commented
Looks good @macolo 

If you change the PR title suffix from "WiP:" to "docs:" it'll pass that failing check.

2022-05-27 22:17 UTC, marksweb approved these changes

2022-10-23 18:51 UTC, fsbraun commented
I took the liberty to update the matrix according to the current state and include Django 4.1 on the list. @marksweb can you re-review this?

2023-01-11 06:26 UTC, fsbraun commented
Updated with release 3.11.1 :-)

2023-01-11 06:26 UTC, closed without merging