Release/3.11.0
django-cms/django-cms pull request #7326
Opened 2022-05-23 21:27 UTC by creyD

## Description

## Related resources

* #...
* #...

## Checklist

* [] I have opened this pull request against ``develop``
* [x] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

2022-05-23 22:57 UTC, marksweb requested changes
Thanks @creyD - this is very nearly ready.

Could you just delete the following directories please?

- `static/cms/css/3.11.0`
- `static/cms/fonts/3.11.0`
- `static/cms/js/dist/3.11.0`

This will leave the PR with just the rc1 static files.

2022-05-24 09:15 UTC, marksweb requested changes

2022-05-24 09:15 UTC, marksweb commented on docs/upgrade/3.11.0.rst
> +This release focuses on Python 3.10, node 16 (for build system), and bug fixes.
Can you please change this to...

```
This release focuses on support for django 4 and dark mode.
```

2022-05-24 09:56 UTC, vinitkumar approved these changes

2022-05-24 10:52 UTC, marksweb approved these changes

2022-05-24 10:52 UTC, merged