test: Run tests against django main branch
django-cms/django-cms pull request #7650
Opened 2023-09-20 19:23 UTC by marksweb

This introduces testing, allowed to fail, against the main branch of django so we have visibility of what is coming in future versions.

2023-09-20 20:44 UTC, fsbraun requested changes
Lines 184 and 185 need to be swapped. Otherwise, the requirements will uninstall the django main branch if there is a `<5` somewhere.

Like wise 232 and 233, and 280 and 281

2023-09-20 20:44 UTC, fsbraun commented on .github/workflows/test.yml
> +        image: postgres:12
```suggestion
        image: postgres:13
```
Django main dropped postgres 12

2023-09-20 20:44 UTC, fsbraun commented on .github/workflows/test.yml
> +        python manage.py test
```suggestion
        python -c "from django import __version__ ; print(f'Django version {__version__}')"
        python manage.py test
``` 
For transparency let's print out which version the django main had...

2023-09-20 20:44 UTC, fsbraun commented on .github/workflows/test.yml
> +        python manage.py test
```suggestion
        python -c "from django import __version__ ; print(f'Django version {__version__}')"
        python manage.py test
```
Same here.

2023-09-20 21:33 UTC, fsbraun approved these changes

2023-09-20 21:36 UTC, fsbraun commented on .github/workflows/test.yml
> +        python -c "from django import __version__ ; print(f'Django version {__version__}')"
```suggestion
```

2023-09-22 16:27 UTC, marksweb commented
@fsbraun have we removed the Django 5 restriction from develop 4? Could do with updating my branches before merging to use it if we've dropped that limit.

2023-09-22 16:29 UTC, fsbraun commented
Just did. But also need to fix ruff... One minute.

2023-09-22 21:57 UTC, merged