Feat/django 5 support
django-cms/django-cms pull request #7724
Opened 2023-12-20 16:55 UTC by protoroto

## Description

This cherry-picks two commits from @fsbraun in develop-4 branch and fixes toolbar tests as Django 5.0 doesn't accepts anymore GET requests for logout view

## Checklist

* [x] I have opened this pull request against ``develop``
* [x] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

2023-12-20 18:41 UTC, protoroto commented
@fsbraun I should've now fix all the build/tests errors, and cleaned up the code a bit

2023-12-20 21:20 UTC, fsbraun requested changes
@protoroto Thanks so much for the PR! I left two small comments.

2023-12-20 21:20 UTC, fsbraun commented on cms/forms/fields.py
> +        super().__init__(*args, **kwargs)
```suggestion
```

Let us not deprecate LazyChoiceField in 3.11. yet.

2023-12-20 21:20 UTC, fsbraun commented on test_requirements/django-5.0.txt
> +Django>=5.0a1,<5.1
```suggestion
Django>=5.0,<5.1
```
Django 5.0 is out now. :-)

2023-12-21 07:50 UTC, protoroto commented
> @protoroto Thanks so much for the PR! I left two small comments.

@fsbraun Thanks, I've done the suggested changes!

2023-12-21 07:52 UTC, fsbraun commented on cms/forms/fields.py
> +                      DeprecationWarning, stacklevel=2)
Sorry, I did not see this. 
```suggestion
```

2023-12-21 07:53 UTC, protoroto commented
@fsbraun No worries, I was going to ask if you wanted SuperLazyIterator not deprecated too ;)

2023-12-21 07:55 UTC, fsbraun approved these changes

2023-12-21 08:55 UTC, protoroto commented
@fsbraun Do you know why the 6 expected checks don't run? It is because their name is changed in `test.yml`? That change was in a commit I cherry-picked from you, but if here we need the "old" names, I'll change them back.

2023-12-21 09:20 UTC, fsbraun commented
No, pls. Keep them.

2023-12-21 09:33 UTC, fsbraun commented
Thanks! I will change the requirements for the repo tests to pass once this is merged.

2023-12-21 12:41 UTC, marksweb commented
> Do you know why the 6 expected checks don't run? It is because their name is changed in `test.yml`?

Yes that's why. The checks get marked as expected, then if their name changes, you end up in this situation but it's not a problem.

2023-12-21 16:06 UTC, protoroto commented
@marksweb @fsbraun Ok, should I do something else here, or it's ok like this?

2023-12-21 17:45 UTC, marksweb commented
@protoroto no, I was just waiting for all the checks to pass.

2023-12-21 18:41 UTC, merged