fix: Redirect user to edit url after a successful page creation
django-cms/django-cms pull request #7772
Opened 2024-01-21 16:15 UTC by sakhawy

## Description
Added the wizard property ``edit_mode_on_success`` and defaulted it to True to redirect newly created pages to edit mode instead of preview mode. The related documentation was updated.

## Related resources

* #7688 

## Checklist

* [X] I have opened this pull request against ``develop-4``
* [X] I have added or modified the tests when changing logic
* [X] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [X] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

2024-01-21 21:07 UTC, fsbraun commented
Hey @sakhawy ! This looks good to me! Just one thing: Should we also test that we get the preview URL if `edit_mode_on_success` is false?

2024-01-21 21:28 UTC, sakhawy commented
@fsbraun Thanks! Done.

2024-01-21 22:43 UTC, fsbraun approved these changes
Well done! Looks good!

2024-01-23 10:27 UTC, marksweb requested changes
Just a minor point.

2024-01-23 18:07 UTC, sakhawy commented on cms/tests/test_wizards.py
> +            title=_(u"Page"),
Thanks!

2024-01-26 23:28 UTC, marksweb approved these changes

2024-01-26 23:28 UTC, merged