fix: CMS widgets need not load if they are read only
django-cms/django-cms pull request #7880
Opened 2024-04-18 15:04 UTC by fsbraun

## Description

In django CMS 4 form fields that use CMS widgets might be read-only (e.g., if the version is published). In that case, widgets are not loaded into `window.CMS.Widgets`. This PR only activates widgets if they are loaded.

Fixes #7879.

This PR does not change any logic (only prevents a js script error to be thrown), hence no tests.

## Related resources

* #7879 
* #...

## Checklist

* [x] I have opened this pull request against ``develop-4``
* [ ] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

2024-04-18 15:39 UTC, jrief commented
Yes, this PR fixes the problem.

For curiosity, is it intended that `window.CMS.Widgets._pageSelectWidgets` might be undefined?

2024-04-18 15:41 UTC, jrief requested changes
Wouldn't it be nicer to write:

```javascript
window.CMS.Widgets?._pageSelectWidgets?.forEach
```

2024-04-18 15:42 UTC, jrief commented on cms/static/cms/js/widgets/forms.pagesmartlinkwidget.js
```
window.CMS.Widgets?._pageSmartLinkWidgets?.forEach
```

2024-04-18 20:39 UTC, fsbraun commented
@jrief Good news. 

I hesitate to use optional chaining, since it is "only" supported by newer browsers (~95% according to can I use). django CMS' whole JS code base does not use it and I reckon the two lines are not worth starting to think about compatibility.

2024-04-23 18:45 UTC, marksweb approved these changes

2024-04-23 19:36 UTC, merged