Fix: Set toolbar direction based on toolbar language
django-cms/django-cms pull request #7902
Opened 2024-05-02 14:58 UTC by fsbraun

## Description

@sakhawy 

This PR sets the toolbar text direction based on the toolbar language and not based on the document language.

This needs a "poylfill" to work with Chrome before 120 which will be added in an additional commit.

## Related resources

* #...
* #...

## Checklist

* [ ] I have opened this pull request against ``develop-4``
* [ ] I have added or modified the tests when changing logic
* [ ] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [ ] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

2024-05-02 15:29 UTC, sakhawy requested changes
Aside from the small comment, LGTM! I tested it on a <120 chrome and the rtl patch is working perfectly!

2024-05-02 15:29 UTC, sakhawy commented on cms/static/cms/sass/components/_toolbar.scss
> -        [dir=rtl] & {
As the comments say, if you didn't set `float` to `none`, if you're on mobile, the `cms-toolbar-item` will float to the right and won't be clickable:
![image](https://github.com/django-cms/django-cms/assets/50373064/01b9423f-38e8-432e-8602-4756b49874af)

2024-05-02 15:34 UTC, fsbraun commented
The patch is minimal, though. We might find places with weird layout. I'll try to add a few more lines later.

2024-05-02 15:37 UTC, sakhawy commented
Alright, I'll do some manual tests later!

2024-05-02 18:35 UTC, fsbraun commented
@sakhawy So, the polyfill should be complete ;-)

2024-05-02 18:36 UTC, fsbraun commented
Once, we have this merged, I'll chery-pick it into #7901

2024-05-05 12:08 UTC, fsbraun commented
@sakhawy Can you give this a final check, so we can merge it. I would love to backport it to 3.11 and include it in 3.11.6 which I am about to release...

2024-05-11 13:32 UTC, sakhawy requested changes
I tested the changes on Firefox 125 and Chrome 110. I also compared it against django-cms 4.1.1. Aside from the small changes, LGTM!

2024-05-11 13:32 UTC, sakhawy commented on cms/static/cms/sass/components/_modal.scss
>  .cms-modal-resize {
I think the resize cursor should also be flipped (and patched in `_rtl_patch.scss`):

```css
    &:dir(rtl) {
        cursor: ne-resize;  // cursor pointing north-east
    }
```

2024-05-11 13:32 UTC, sakhawy commented on cms/static/cms/sass/components/_modal.scss
> +            transform: scale(-1,1) translate(2px, 0);  // flip drag triangle
I don't think this is patched in `_rtl_patch.scss`

2024-05-11 17:23 UTC, fsbraun commented
Well spotted, thank you!

2024-05-12 06:22 UTC, fsbraun commented
@sakhawy Fixed both resize cursor and missing polyfill patch. If you're good to go, let me know by approving the PR :-)

2024-05-12 14:07 UTC, sakhawy approved these changes
LGMT, thanks!

2024-05-12 14:07 UTC, sakhawy commented on cms/static/cms/sass/libs/_rtl_patch.scss
> +    cursor: nw-resize;
Just a tiny change, this should be "n**e**-resize"

2024-05-12 17:10 UTC, marksweb approved these changes
Happy to approve with Moe's approval in place 👏

2024-05-12 17:45 UTC, merged