docs: Improve explanation on how to use templates with django CMS
django-cms/django-cms pull request #7929
Opened 2024-05-25 16:44 UTC by fsbraun

## Description

People have struggled to understand how templates work with django CMS. Since both the quickstarter project and the project template for the `djangocms` command include a dummy template configuration, it might easily appear insufficiently transparent how to use templates with django CMS.

This PR adds some basic information to the "How to work with templates" section. I tried to focus on the main points.

**Please feel free to directly add more stuff you think is needed or to explain things better!**

Directly change the PR or add comments here, please!

## Related resources

* #...
* #...

## Checklist

* [x] I have opened this pull request against ``develop-4``
* [x] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined the channel #pr-reviews on our [Discord Server](https://discord-pr-review-channel.django-cms.org) to find a “pr review buddy” who is going to review my pull request.

2024-05-25 18:15 UTC, marksweb requested changes

2024-05-25 18:15 UTC, marksweb commented on docs/how_to/04-templates.rst
> +django CMS uses Django's template system to manage the layout of the pages. While
"While" needs removing because what comes next is the title for the next section

2024-05-25 21:11 UTC, marksweb approved these changes

2024-05-27 08:37 UTC, macolo commented on docs/how_to/04-templates.rst
> +Since some content repeats on multiple pages, it is useful to create a static
Alternative:

> The package `[djangocms-aliases](https://github.com/django-cms/djangocms-alias)` provides an admin page in `django admin` where special types of placeholders called "static aliases" can be managed and its contents edited.

Frequent Use Cases:
> 1) Editors wish to manage repeated content centrally (DRY - don't repeat yourself)
> 2) Developers wish to add CMS functionality to their custom application's templates
> 
>  **Repeated content**: Often, content areas such as a footer, a header or a sidebar have identical content across all pages of a website. `djangocms-aliases` provides a django admin page for editors to manage such general site-wide content in one place.
> 
> **Custom applications**: Templates in custom applications usually follow some well-defined business logic which is normally hard-coded in the template. However the same templates might include areas of "static" content, i.e. content that editors wish to manage. As django CMS `Placeholder` tags only work in templates attached to the django CMS `Page` model, `djangocms-aliases` closes the gap by providing editors central access to such custom content areas.

2024-05-27 10:07 UTC, fsbraun commented on docs/how_to/04-templates.rst
> +Since some content repeats on multiple pages, it is useful to create a static
Thanks, @macolo ! I added your suggestion!

2024-05-29 19:04 UTC, merged